name: Node Lint And Format

on: push

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: beauwilliams/run-node-formatter@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
